image: docker:latest

stages:
  - build
  - unittest
  - deploy

build:
  stage: build
  # image: docker:git
  services:
    - docker:dind
  script:
    - docker_hub_login
    - docker build -t "$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG"

test:
  stage: unittest
  services:
    - docker:dind
  script:
    - docker run "$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG" python -m unittest discover -s tests/

deploy:
  stage: deploy
  services:
    - docker:dind
  script:
    - helm ls


.helper_functions: &helper_functions |
function docker_hub_login() {
  docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
}

function docker_host_connect() {
  if ! docker info &>/dev/null; then
    if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
      export DOCKER_HOST='tcp://localhost:2375'
    fi
  fi
}

function install_helm() {
  apk add -U openssl curl tar gzip bash ca-certificates git
  curl https://kubernetes-helm.storage.googleapis.com/helm-v2.7.2-linux-amd64.tar.gz | tar zx
  mv linux-amd64/helm /usr/bin/
}
docker_host_connect

before_script:
  - *helper_functions